---
categories:
- category
date: 2017-01-14T13:54:58+09:00
description: ""
tags:
- tag1
- tag2
title: "multico_1"
author: "kanji14134"
---

Row
-------------------------------------
    
### Chart 1
    今持っているデータが多重共線性のあるデータで変数選択に苦しんでいます。  
変数選択以外の回避法を調べると、リッジ回帰なら大丈夫!みたいな記述があり、  
階層ベイズでリッジ回帰的なのもできるよとのことなので、  
多重共線性のあるデータで真値が推定できるかやってみたいと思います。 ?

## データ生成
適当にRでつくります。が、けっこう大変でした。  
x1~x4の4つの説明変数と、目的変数yを作ります。  
係数の真値は全て2にしてみます。切片は平均1、分散1の正規分布からなります。  

$$
y = 2*x1+2*x2+2*x3+2*x4+N(1,1)
$$

$$
y_{i}=ax_{i}+b
$$


```{r}
require(dplyr);require(magrittr)
nobs <- 100
M <- matrix(c(1, 0.95, 0.95, 0.95,
             0.95, 1, 0.95, 0.95,
             0.95, 0.95, 1, 0.95,
             0.95, 0.95, 0.95, 1), nrow<-4, ncol<-4)
L <- chol(M)
nvars <- dim(L)[1]
set.seed(0)
L %>% 
  t() %*% #help ?'%*%'
  matrix(rnorm(nvars*nobs), nrow=nvars, ncol=nobs) %>% 
  t() %>% 
  data.frame() %>% 
  set_colnames(c('x1', 'x2', 'x3', 'x4')) -> dat
dat %>% head
```
   
Row
-------------------------------------
    
### Chart 2
    
```{r}

```
    
### Chart 3

```{r}

```
