---
title: GISデータ入手先一覧
author: kanji14134
date: '2018-12-02'
slug: gis
categories: [GIS]
tags: []
description: ''
---

各機関・組織で**無料で公開**されているGISデータを中心に、
研究に使えるものをあつめました。  
みんなもRで地理情報データを解析しよう!!  

**随時更新予定**

### 基盤地図情報
[リンク](https://fgd.gsi.go.jp/download/menu.php)  
日本全国の(多分)地形図と同じベクターデータがXMLで提供されています。
ただし細かく分割されていますので、全国のデータをざっと見るには適していないかもしれません。  

- 道路
- 建物形状
- 開放水域 等など

標高データ

- 10mメッシュ(全国)
- 5mメッシュ(河川周辺地域)

いずれも専用のGISフォーマットへの変換ツールがありますが、  
Rで変換する方法をuri先生が開発して下さっております。[リンク](https://uribo.hatenablog.com/entry/2018/11/19/081000)

### 国土数値情報
[リンク](http://nlftp.mlit.go.jp/ksj/)

- 平年値気象メッシュ
- 市区町村区域
- 土地利用
- 公共施設位置
- 自然公園地域 等

ESRI Shapefile形式で提供されるデータです。  
とりあえずここのデータを眺めると目当てのものが見つかります。  
こちらはR上でデータ取得までできてしまうRパッケージがyutani先生より公開されております。[リンク](https://github.com/yutannihilation/kokudosuuchi)

### 植生図
[リンク](http://gis.biodic.go.jp/webgis/sc-023.html)

植生のGISデータがESRI Shapefile形式で提供されています。  
航空写真判読と現地調査をもとに、森林や草地の植生が細かく分けられています。  

### 土地保全図
[リンク](http://nrb-www.mlit.go.jp/kokjo/inspect/landclassification/download/index.html) 

- 地形分類図
- 土壌図
- 地質図

ここではおおまかな地質図などを手に入れることができます。

### 海外
[リンク](http://www.diva-gis.org/gdata)  
海外のデータをざっと見るにはこちらがおすすめです。
DIVA-GISというOSSのページになります。  

- 行政区画
- 人口
- 河川
- 道路等

### OpenStreetMap
[リンク](https://www.openstreetmap.org/)
OpenStreetMapはご存知でしょうか?**leaflet**の背景になっていたりする、  
オープンなGISデータです。もちろんダウンロードすることもできます。  
ログインしてExportを押せば、表示地域のデータが、OSMファイルとしてダウンロードできます。  
このデータはGDALで変換できます。

関連ページ  
[衛星画像データ入手先](../%E8%A1%9B%E6%98%9F%E7%94%BB%E5%83%8F%E5%85%A5%E6%89%8B%E5%85%88%E4%B8%80%E8%A6%A7/)